# Part 1 — Inspect & Understand the Dataset

In [448]:
import pandas as pd
import numpy as np

In [449]:
# Q1. Load the dataset 
df_og = pd.read_csv("/Users/abhinavkanchustambham/Documents/programming/DS/python/Tasks/customer_analytics.csv")
df = df_og.copy()
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 0:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 0:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 0:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 0:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 0:00:00,Yes,Medium,11472.36,124,9.1

In [450]:
# Q2. Inspect the end of the dataset 
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 0:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 0:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 0:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 0:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 0:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 0:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 0:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 0:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 0:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 0:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [451]:
# Q3. Random inspection 
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
70,101126,75,178686,5144.93,446,14,pune,Premium,Agent,2024-12-28 0:00:00,No,High,45017.3,29,7.7
940,100132,56,NaN,250644.07,433,3,Delhi,Retail,Mobile,2022-10-09 0:00:00,Yes,High,25287.39,107,5.9
1222,100689,49,169539,150326.36,617,5,Bangalore,Corporate,Branch,2024-10-05 0:00:00,Yes,Medium,14622.24,121,1.2
470,100293,53,81985,191127.25,687,10,Bangalore,Corporate,Online,2024-04-19 0:00:00,No,Medium,11277.59,145,6.4
1955,101105,31,NaN,-,530,12,Bangalore,SME,Branch,2022-07-27 0:00:00,Yes,High,36369.25,64,3.1
929,100800,56,195604,185174.71,454,15,Mumbai,Premium,Online,2023-05-21 0:00:00,Yes,High,46418.1,81,8.7
1141,101405,64,206360,191128.41,427,15,NaN,Corporate,Agent,NaN,Yes,High,48616.42,92,8.3
158,101858,54,204526,4090.21,601,11,Delhi,Corporate,Branch,2021-05-05 0:00:00,Yes,High,40940.68,24,4.2
540,100372,50,27920,118420.31,847,6,Hyderabad,Premium,Agent,2024-08-28 0:00:00,Yes,Low,47061.51,103,7.8
1037,101362,19,93099,13635.75,369,0,NaN,NaN,Mobile,2022-07-24 0:00:00,Yes,High,16640.49,57,2.5

In [452]:
# Q4. Dataset audit 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [453]:
# Q5. Missing-value audit 
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [454]:
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

# Part 2 — Detect & Fix Data Quality Problems

In [455]:
# Q6. Duplicate investigation 
print("Number of duplicate rows:",df.duplicated().sum())

Number of duplicate rows: 40

In [456]:
# Q7. Remove duplicates
df = df.drop_duplicates()
print("Number of duplicate rows After removing duplicates:",df.duplicated().sum())

Number of duplicate rows After removing duplicates: 0

In [457]:
# Q8. Numeric column investigation 
potentially_numeric = ['Age' , 'Annual_Income' , 'Account_Balance' , 'Credit_Score' , 'Monthly_Spend' , 'Transactions']
df.select_dtypes(['int64','float64'])

      Customer_ID  Tenure_Years  Satisfaction_Score
0          101317             3                 3.1
1          101001             8                 8.2
2          101069            12                 6.3
3          101968            14                 9.7
4          100530             4                 3.7
...           ...           ...                 ...
2035       101131            12                 8.6
2036       101295             8                 2.6
2037       100861             8                 1.3
2038       101460             8                 9.3
2039       101127             6                 3.1

[2000 rows x 3 columns]

In [458]:
# Q9. Fix Age
df['Age'] = pd.to_numeric(df['Age'],errors = "coerce")
median = df['Age'].median()
print("median of the age in the dataset:",median)
df['Age'] = df['Age'].fillna(median)

median of the age in the dataset: 47.0

In [459]:
# Q10. Fix Annual Income 
df['Annual_Income'] = pd.to_numeric(df['Annual_Income'] , errors="coerce")
df['Annual_Income'].astype('float64')
median = df['Annual_Income'].median()
print("median of the Annual Income in the dataset:",median)
df['Annual_Income'] = df['Annual_Income'].fillna(median)
# df['Annual_Income'].head(50)

median of the Annual Income in the dataset: 139914.0

In [460]:
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

# Part 3 — Numerical Cleaning

In [461]:
# Q11. Clean Account Balance 
df['Account_Balance'] = pd.to_numeric(df['Account_Balance'] , errors='coerce')
mean = df['Account_Balance'].mean()
print(f"mean of the total account balance is {mean}")
df['Account_Balance'] =df['Account_Balance'].fillna(mean)
# df['Account_Balance'].head(50)

mean of the total account balance is 151344.55801855895

In [462]:
# Q12. Clean Credit Score 
df['Credit_Score'] = pd.to_numeric(df['Credit_Score'] , errors='coerce')
median = df['Credit_Score'].median()
print("median of the Credit Score in the dataset:",median)
df['Credit_Score'] = df['Credit_Score'].fillna(median)
df['Credit_Score'] = df['Credit_Score'].astype('int64')
df['Credit_Score'].dtypes
# df['Credit_Score'].head(100)

median of the Credit Score in the dataset: 570.5

dtype('int64')

In [463]:
# Q13. Clean Monthly Spend 
df['Monthly_Spend'] = pd.to_numeric(df['Monthly_Spend'],errors="coerce")
median = df['Monthly_Spend'].median()
print("median of the Monthly Spendings in the dataset:",median)
df['Monthly_Spend'] = df['Monthly_Spend'].fillna(median)
df['Monthly_Spend'].dtypes

median of the Monthly Spendings in the dataset: 24625.17

dtype('float64')

In [464]:
# Q14. Clean Transactions 

df['Transactions'] = pd.to_numeric(df['Transactions'],errors="coerce")
median = df['Transactions'].median()
print("median of the Transactions in the dataset:",median)
df['Transactions'] = df['Transactions'].fillna(median)
df['Transactions'] = df['Transactions'].astype('int64')
df['Transactions'].dtypes

median of the Transactions in the dataset: 76.0

dtype('int64')

In [465]:
# Q15. Clean Satisfaction Score 

df['Satisfaction_Score'] = pd.to_numeric(df['Satisfaction_Score'],errors="coerce")
mean = df['Satisfaction_Score'].median()
print("mean of the Satisfaction Score in the dataset:",mean)
df['Satisfaction_Score'] = df['Satisfaction_Score'].fillna(mean)
df['Satisfaction_Score'] = df['Satisfaction_Score'].astype('float64')
df['Satisfaction_Score'].dtypes

mean of the Satisfaction Score in the dataset: 5.7

dtype('float64')

# Part 4 — Date Cleaning

In [466]:
# Q16. Investigate Join_Date
df["Join_Date"].head()
df["Join_Date"].isnull().sum()

np.int64(100)

In [467]:
# Q17. Convert Join_Date 
df["Join_Date"] = pd.to_datetime(df['Join_Date'], yearfirst= True , errors="coerce")
df["Join_Date"].head(50)

0    2022-08-15
1    2025-01-11
2    2024-08-01
3    2021-05-15
4    2026-02-03
5    2023-06-04
6    2024-01-16
7    2024-06-26
8    2025-03-12
9    2021-10-07
10   2023-03-02
11   2025-11-22
12   2021-06-25
13   2025-11-19
14   2025-08-26
15   2024-05-05
16   2022-01-07
17   2022-05-25
18   2022-10-07
19   2023-08-10
20          NaT
21   2022-02-13
22   2025-04-23
23   2021-11-17
24   2025-03-06
25   2026-03-02
26   2022-06-21
27   2023-04-30
28   2024-09-13
29   2025-11-11
30   2024-06-02
31   2021-01-31
32   2024-04-20
33   2025-04-10
34   2023-08-04
35   2023-08-27
36   2024-12-07
37   2021-07-22
38   2024-03-24
39   2021-05-12
40   2021-11-18
41   2025-07-11
42   2022-03-10
43   2023-08-22
44   2022-01-25
45   2024-10-04
46   2024-09-02
47   2025-07-30
48   2022-08-13
49   2025-11-27
Name: Join_Date, dtype: datetime64[ns]

In [468]:
# Q18. Handle missing dates
median = df['Join_Date'].median()
df['Join_Date'] = df['Join_Date'].fillna(median)
df['Join_Date'].head()

0   2022-08-15
1   2025-01-11
2   2024-08-01
3   2021-05-15
4   2026-02-03
Name: Join_Date, dtype: datetime64[ns]

# Part 5 — Categorical Cleaning

In [469]:
# Q19. Clean City
df = df.replace({"City" : {"Mumbai":"Mumbai" , "mumbai":"Mumbai",
                          "Hyderabad":"Hyderabad","hyderabad":"Hyderabad",
                          "Delhi":"Delhi","delhi":"Delhi",
                          "Kolkata":"Kolkata" , "kolkata":"Kolkata",
                          "Pune":"Pune" , "pune":"Pune",
                          "Chennai":"Chennai" , "chennai":"Chennai",
                          "Bangalore":"Bangalore" , "bangalore":"Bangalore"}})
df['City'].value_counts()

City
Mumbai       308
Hyderabad    292
Delhi        283
Kolkata      274
Pune         270
Bangalore    247
Chennai      246
Name: count, dtype: int64

In [470]:
# Q20. Analyze Segment 
print(f"Null values present in the segment column :{df['Segment'].isnull().sum()}")
df['Segment'].value_counts()
df['Segment'] = df['Segment'].fillna('SME')
df['Segment'].value_counts()

Null values present in the segment column :100

Segment
SME          548
Premium      516
Retail       468
Corporate    468
Name: count, dtype: int64

In [471]:
# Q21. Clean Active 

df = df.replace({"Active" : {"YES":"Yes" , "Yes":"Yes" , "Y":"Yes" , "yes":"Yes" , "1":"Yes" , 
                             "NO":"No" , "No":"No" , "N":"No" , "no":"No" , "0":"No"}})
df['Active'].value_counts()

Active
Yes    1345
No      597
Name: count, dtype: int64

In [472]:
# Q22. Clean Risk_Level 

print(f"Null values present in the Active column :{df['Risk_Level'].isnull().sum()}")
df['Risk_Level'].value_counts()

Null values present in the Active column :0

Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64

In [473]:
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1

# Part 6 — Column Transformation

In [474]:
# Q23. Rename columns 
df = df.rename(columns=  {"Customer_ID":"Customer_ID" , "Annual_Income":"AnnualIncome" , "Account_Balance":"AccountBalance" ,
"Credit_Score":"CreditScore" , "Tenure_Years":"Tenure" , "Join_Date":"CustomerJoinDate" , "Risk_Level":"RiskLevel" ,
"Monthly_Spend":"MonthlySpend" , "Satisfaction_Score":"SatisfactionScore" })
df.head()

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7

In [475]:
# Q24. Add a prefix 
df_prefix = df.add_prefix("Customer_")
df_prefix.head()

,Customer_Customer_ID,Customer_Age,Customer_AnnualIncome,Customer_AccountBalance,Customer_CreditScore,Customer_Tenure,Customer_City,Customer_Segment,Customer_Channel,Customer_CustomerJoinDate,Customer_Active,Customer_RiskLevel,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7

In [476]:
# Q25. Remove unnecessary column
df_ni = df.copy()
df_ni = df_ni.drop('Customer_ID',axis=1)
df_ni.head()

,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore
0,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,67.0,31570.0,242423.78,370,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7

In [477]:
df

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1

# Part 7 — Create New Columns

In [478]:
# Q26. Create Annual Income in Lakhs 
df['Income_Lakhs'] = df['AnnualIncome'] / 100000
df.head(10)

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1,0.44033
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2,2.15546
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3,2.26403
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7,0.87824
4,100530,67.0,31570.0,242423.78,370,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7,0.31570
5,101334,68.0,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04,Yes,Low,15121.16,6,8.5,0.37087
6,100415,47.0,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16,Yes,High,17655.61,31,2.8,0.67229
7,100983,65.0,139914.0,61030.94,554,15,Kolkata,SME,Agent,2024-06-26,Yes,Medium,1720.85,139,9.7,1.39914
8,100417,63.0,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12,Yes,High,38043.07,76,7.1,1.53267
9,101472,42.0,139914.0,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07,Yes,Medium,11472.36,124,9.1,1.39914

In [479]:
# Q27. Create Monthly Income
df['MonthlyIncome'] = df['AnnualIncome'] / 12
df['Income_After_Spending'] = df['MonthlyIncome'] - df['MonthlySpend']
df.sample(10)

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending
779,101801,34.0,137782.0,151344.558019,509,8,Hyderabad,Premium,Mobile,2024-07-25,Yes,High,19528.24,62,8.5,1.37782,11481.833333,-8046.406667
927,100637,18.0,132522.0,44880.430000,814,3,Mumbai,Retail,Mobile,2022-01-31,NaN,Low,15886.88,37,10.0,1.32522,11043.500000,-4843.380000
942,100410,47.0,201422.0,22915.480000,471,12,Hyderabad,Corporate,Branch,2022-08-31,Yes,High,13678.30,140,1.7,2.01422,16785.166667,3106.866667
1449,100769,67.0,65390.0,137406.660000,378,3,NaN,Corporate,Mobile,2021-02-20,No,High,48870.55,64,5.8,0.65390,5449.166667,-43421.383333
164,100212,50.0,224988.0,17841.470000,762,6,Mumbai,Retail,Mobile,2023-10-23,No,Low,49510.43,67,5.0,2.24988,18749.000000,-30761.430000
1785,101716,63.0,34752.0,248206.970000,370,6,Pune,Retail,Branch,2021-03-22,No,High,48215.69,2,2.4,0.34752,2896.000000,-45319.690000
971,100334,26.0,184033.0,12687.520000,508,14,Bangalore,Corporate,Branch,2023-05-18,Yes,High,24625.17,101,5.7,1.84033,15336.083333,-9289.086667
791,101978,66.0,111795.0,59291.770000,736,7,Chennai,Premium,Mobile,2024-05-08,Yes,Low,585.38,114,4.9,1.11795,9316.250000,8730.870000
1504,100791,48.0,185443.0,112066.440000,479,11,Delhi,Retail,Agent,2023-08-24,Yes,High,32235.41,55,9.3,1.85443,15453.583333,-16781.826667
253,100531,59.0,139914.0,53366.440000,547,12,Mumbai,Retail,Branch,2025-09-29,Yes,High,44915.49,114,7.4,1.39914,11659.500000,-33255.990000

In [480]:
# Q28. Create Balance-to-Income Ratio
# try:
#     df['Balance_Income_Ratio'] = df['AccountBalance'] / df['AnnualIncome']
#     df.sample(10)
# except Exception as e:
#     print(e)

df['Balance_Income_Ratio'] = df['AccountBalance'] / df['AnnualIncome']
df.sample(10)

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
1311,100173,49.0,77307.0,44395.240000,837,11,Kolkata,Corporate,Online,2021-08-13,Yes,Low,23565.35,75,9.7,0.77307,6442.250000,-17123.100000,0.574272
1782,100442,75.0,60046.0,159221.210000,660,5,Bangalore,Premium,Agent,2024-03-12,No,Medium,25989.89,138,7.4,0.60046,5003.833333,-20986.056667,2.651654
1831,101267,32.0,202558.0,118712.390000,679,9,Kolkata,Premium,Agent,2024-02-05,Yes,Medium,46428.19,119,4.6,2.02558,16879.833333,-29548.356667,0.586066
860,101554,20.0,87032.0,278430.550000,791,15,Mumbai,SME,Agent,2023-08-20,No,Low,40010.06,56,2.7,0.87032,7252.666667,-32757.393333,3.199174
490,100495,68.0,239266.0,149470.800000,550,12,Chennai,Corporate,Mobile,2024-06-06,No,Medium,12802.53,71,1.6,2.39266,19938.833333,7136.303333,0.624706
1977,100841,35.0,217035.0,119234.450000,311,10,Delhi,SME,Online,2022-06-15,No,High,18126.44,7,7.2,2.17035,18086.250000,-40.190000,0.549379
1068,100067,24.0,139914.0,151344.558019,324,1,Bangalore,SME,Branch,2023-02-15,Yes,High,9814.64,54,8.3,1.39914,11659.500000,1844.860000,1.081697
1615,100158,20.0,169097.0,249206.550000,568,4,Kolkata,Corporate,Mobile,2025-03-10,Yes,Medium,48568.09,89,9.2,1.69097,14091.416667,-34476.673333,1.473749
986,101504,24.0,65785.0,151344.558019,664,9,Chennai,Retail,Agent,2023-02-12,Yes,Medium,10041.34,29,4.1,0.65785,5482.083333,-4559.256667,2.300594
36,100030,29.0,139914.0,89018.290000,389,3,Chennai,SME,Mobile,2024-12-07,Yes,High,24646.77,64,1.0,1.39914,11659.500000,-12987.270000,0.636236

In [481]:
df.to_csv("clean.csv")

# Part 8 — Final Real-World Cleaning Challenge

In [482]:
# Q29. Prepare the ML-ready dataset 
import pandas as pd
import numpy as np
df_og = pd.read_csv("/Users/abhinavkanchustambham/Documents/programming/DS/python/Tasks/customer_analytics.csv")
df = df_og.copy()
df.head(10)
df.tail(10)
df.sample(10)
df.info()
df.isnull().sum()
print("Number of duplicate rows:",df.duplicated().sum())
df = df.drop_duplicates()
print("Number of duplicate rows After removing duplicates:",df.duplicated().sum())
df.select_dtypes(['int64','float64'])
df['Age'] = pd.to_numeric(df['Age'],errors = "coerce")
median = df['Age'].median()
print("median of the age in the dataset:",median)
df['Age'] = df['Age'].fillna(median)
df['Annual_Income'] = pd.to_numeric(df['Annual_Income'] , errors="coerce")
df['Annual_Income'].astype('float64')
median = df['Annual_Income'].median()
print("median of the Annual Income in the dataset:",median)
df['Annual_Income'] = df['Annual_Income'].fillna(median)
df['Account_Balance'] = pd.to_numeric(df['Account_Balance'] , errors='coerce')
mean = df['Account_Balance'].mean()
print(f"mean of the total account balance is {mean}")
df['Account_Balance'] =df['Account_Balance'].fillna(mean)
df['Credit_Score'] = pd.to_numeric(df['Credit_Score'] , errors='coerce')
median = df['Credit_Score'].median()
print("median of the Credit Score in the dataset:",median)
df['Credit_Score'] = df['Credit_Score'].fillna(median)
df['Credit_Score'] = df['Credit_Score'].astype('int64')
df['Credit_Score'].dtypes
df['Monthly_Spend'] = pd.to_numeric(df['Monthly_Spend'],errors="coerce")
median = df['Monthly_Spend'].median()
print("median of the Monthly Spendings in the dataset:",median)
df['Monthly_Spend'] = df['Monthly_Spend'].fillna(median)
df['Monthly_Spend'].dtypes
df['Transactions'] = pd.to_numeric(df['Transactions'],errors="coerce")
median = df['Transactions'].median()
print("median of the Transactions in the dataset:",median)
df['Transactions'] = df['Transactions'].fillna(median)
df['Transactions'] = df['Transactions'].astype('int64')
df['Transactions'].dtypes
df['Satisfaction_Score'] = pd.to_numeric(df['Satisfaction_Score'],errors="coerce")
mean = df['Satisfaction_Score'].median()
print("mean of the Satisfaction Score in the dataset:",mean)
df['Satisfaction_Score'] = df['Satisfaction_Score'].fillna(mean)
df['Satisfaction_Score'] = df['Satisfaction_Score'].astype('float64')
df['Satisfaction_Score'].dtypes
df["Join_Date"].head()
df["Join_Date"].isnull().sum()
df["Join_Date"] = pd.to_datetime(df['Join_Date'], yearfirst= True , errors="coerce")
df["Join_Date"].head(50)
median = df['Join_Date'].median()
df['Join_Date'] = df['Join_Date'].fillna(median)
df['Join_Date'].head()
df = df.replace({"City" : {"Mumbai":"Mumbai" , "mumbai":"Mumbai",
                          "Hyderabad":"Hyderabad","hyderabad":"Hyderabad",
                          "Delhi":"Delhi","delhi":"Delhi",
                          "Kolkata":"Kolkata" , "kolkata":"Kolkata",
                          "Pune":"Pune" , "pune":"Pune",
                          "Chennai":"Chennai" , "chennai":"Chennai",
                          "Bangalore":"Bangalore" , "bangalore":"Bangalore"}})
df['City'].value_counts()

print(f"Null values present in the segment column :{df['Segment'].isnull().sum()}")
df['Segment'].value_counts()
df['Segment'] = df['Segment'].fillna('SME')
df['Segment'].value_counts()
df = df.replace({"Active" : {"YES":"Yes" , "Yes":"Yes" , "Y":"Yes" , "yes":"Yes" , "1":"Yes" , 
                             "NO":"No" , "No":"No" , "N":"No" , "no":"No" , "0":"No"}})
df['Active'].value_counts()
print(f"Null values present in the Active column :{df['Risk_Level'].isnull().sum()}")
df['Risk_Level'].value_counts()

df = df.rename(columns=  {"Customer_ID":"Customer_ID" , "Annual_Income":"AnnualIncome" , "Account_Balance":"AccountBalance" ,
"Credit_Score":"CreditScore" , "Tenure_Years":"Tenure" , "Join_Date":"CustomerJoinDate" , "Risk_Level":"RiskLevel" ,
"Monthly_Spend":"MonthlySpend" , "Satisfaction_Score":"SatisfactionScore" })
df.head()
df_prefix = df.add_prefix("Customer_")
df_prefix.head()
df_ni = df.copy()
df_ni = df_ni.drop('Customer_ID',axis=1)
df_ni.head()
df['Income_Lakhs'] = df['AnnualIncome'] / 100000
df.head(10)
df['MonthlyIncome'] = df['AnnualIncome'] / 12
df['Income_After_Spending'] = df['MonthlyIncome'] - df['MonthlySpend']
df.sample(10)
df['Balance_Income_Ratio'] = df['AccountBalance'] / df['AnnualIncome']
df.sample(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB
Number of duplicate rows: 40
Number of duplicate rows After removing duplicates: 0
median of the age in the dataset: 47.0
median of the Annual Income in the dataset: 139914.0
mean of the total account balance is 151344.55801855895
median of the Credit Score in the dataset: 570.5
median of the Monthly Spendings in the dataset: 24625.17
median of the Transactions in the dataset: 76.0
mean of the Satisfaction Score in the dataset: 5.7
Null values present in the segment column :100
Null values present in the Active column :0

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
1654,101416,47.0,201325.0,136685.750000,648,8,Bangalore,SME,Online,2025-04-06,Yes,Medium,24625.17,120,6.6,2.01325,16777.083333,-7848.086667,0.678931
62,101898,46.0,79869.0,127781.310000,504,15,Bangalore,SME,Branch,2022-07-22,Yes,High,24625.17,13,5.6,0.79869,6655.750000,-17969.420000,1.599886
1107,101511,39.0,127304.0,9533.550000,731,8,Delhi,Retail,Online,2024-03-17,Yes,High,24343.27,46,9.0,1.27304,10608.666667,-13734.603333,0.074888
625,101913,18.0,90087.0,83353.550000,850,1,Delhi,SME,Mobile,2025-06-06,Yes,Low,3944.30,95,6.9,0.90087,7507.250000,3562.950000,0.925256
360,101426,54.0,170544.0,26696.910000,741,5,Pune,Retail,Agent,2024-12-01,Yes,Low,24625.17,8,4.4,1.70544,14212.000000,-10413.170000,0.156540
1929,101276,61.0,33706.0,59773.790000,570,8,Mumbai,Premium,Agent,2022-08-20,Yes,Low,41641.17,14,1.1,0.33706,2808.833333,-38832.336667,1.773387
1272,101036,68.0,52605.0,62172.690000,368,6,Bangalore,Retail,Mobile,2021-03-26,No,High,44013.57,53,5.7,0.52605,4383.750000,-39629.820000,1.181878
35,100325,66.0,169701.0,151344.558019,429,9,Mumbai,Corporate,Branch,2023-08-27,No,High,17572.01,128,3.9,1.69701,14141.750000,-3430.260000,0.891831
665,100632,68.0,134834.0,299863.180000,846,7,Kolkata,Premium,Branch,2025-11-20,NaN,Low,27872.29,59,7.2,1.34834,11236.166667,-16636.123333,2.223943
429,100571,33.0,126376.0,168997.390000,593,10,Delhi,Retail,Online,2023-08-24,Yes,Medium,27776.05,61,5.1,1.26376,10531.333333,-17244.716667,1.337259

In [447]:
df

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1,0.44033,3669.416667,-19396.773333,2.528805
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2,2.15546,17962.166667,-6663.003333,1.180158
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3,2.26403,18866.916667,-9669.423333,0.706596
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7,0.87824,7318.666667,-5551.043333,3.367435
4,100530,67.0,31570.0,242423.78,370,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7,0.31570,2630.833333,-31532.186667,7.678929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6,0.88530,7377.500000,-1077.920000,1.733771
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6,2.05738,17144.833333,-16942.856667,1.317158
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3,2.11994,17666.166667,-8852.573333,0.757133
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3,0.30105,2508.750000,-18434.360000,1.066838
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1,2.48332,20694.333333,-27816.986667,1.107312