In [1]:
import pandas as pd

In [2]:
# 1
df = pd.read_csv("/Users/abhinavkanchustambham/Documents/programming/DS/python/Tasks/Bank_customer_churn.csv")
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [3]:
# 2
df.tail(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# 3
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
558,559,15717046,Wentworth-Shields,741,Spain,Male,53,3,0.00,2,1,1,38913.68,0
4720,4721,15780654,Sergeyev,619,Germany,Female,33,3,100488.92,2,0,1,36446.74,0
5459,5460,15617507,Wilson,530,Spain,Female,36,7,0.00,2,1,0,80619.09,0
1460,1461,15657085,Gardiner,578,France,Male,23,10,88980.32,1,1,1,125222.36,0
4162,4163,15673584,Bell,652,France,Female,74,5,0.00,2,1,1,937.15,0
9708,9709,15604515,Yefremov,737,Germany,Female,22,10,111543.26,2,0,0,106327.85,0
2410,2411,15613326,Gow,596,France,Female,33,1,138162.81,1,1,0,85412.54,0

In [5]:
# 4
df.info()
len(df.columns)
# df.dtypes
df.isna()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
# 5
df.isnull()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
# 6
df.select_dtypes('int')

,RowNumber,CustomerId,CreditScore,Age,Tenure,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,1,15634602,619,42,2,1,1,1,1
1,2,15647311,608,41,1,1,0,1,0
2,3,15619304,502,42,8,3,1,0,1
3,4,15701354,699,39,1,2,0,0,0
4,5,15737888,850,43,2,1,1,1,0
...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,2,1,0,0
9996,9997,15569892,516,35,10,1,1,1,0
9997,9998,15584532,709,36,7,1,0,1,1
9998,9999,15682355,772,42,3,2,1,0,1
9999,10000,15628319,792,28,4,1,1,0,0

In [8]:
# 7
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [9]:
# 8
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [10]:
# 9
df.drop_duplicates()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [11]:
# 10
df['Exited'].value_counts(1)

Exited
0    0.7963
1    0.2037
Name: proportion, dtype: float64

In [12]:
# 11
df = df.rename(columns = {"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary","Exited":"Churn"})
df

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [13]:
# 12
df = df.add_prefix("Bank_")
df

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [14]:
# 13
df['Bank_Age'] = df['Bank_Age'].astype('float')
df

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [15]:
# 14
df['Bank_Churn'] = df['Bank_Churn'].astype('string')
df.dtypes
# df

Bank_RowNumber                  int64
Bank_Customer_ID                int64
Bank_Surname                   object
Bank_Credit_Score               int64
Bank_Geography                 object
Bank_Gender                    object
Bank_Age                      float64
Bank_Tenure                     int64
Bank_Balance                  float64
Bank_NumOfProducts              int64
Bank_HasCrCard                  int64
Bank_IsActiveMember             int64
Bank_Salary                   float64
Bank_Churn             string[python]
dtype: object

In [16]:
# 15
import numpy as np
salary = [10_000,np.nan,20_000,37_000,45_000,np.nan,1_50_000]

df2 = pd.DataFrame(salary)
salary_mean = df2.mean()
salary_mean
df2.fillna(salary_mean,inplace = True)
df2

          0
0   10000.0
1   52400.0
2   20000.0
3   37000.0
4   45000.0
5   52400.0
6  150000.0

In [17]:
# 16
df2 = pd.DataFrame(salary)
salary_median = df2.median()
salary_median
df2.fillna(salary_median,inplace = True)
df2

          0
0   10000.0
1   37000.0
2   20000.0
3   37000.0
4   45000.0
5   37000.0
6  150000.0

In [18]:
# 17
df.head(5)

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [19]:
# 18
df1 = df.drop("Bank_RowNumber",axis=1)
df1 = df1.drop("Bank_Customer_ID",axis=1)
df1 = df1.drop("Bank_Surname",axis=1)
df1

,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [20]:
# 19
df1 = df1.drop("Bank_Geography",axis=1)
df1

,Bank_Credit_Score,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,619,Female,42.0,2,0.00,1,1,1,101348.88,1
1,608,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,502,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,699,Female,39.0,1,0.00,2,0,0,93826.63,0
4,850,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...
9995,771,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,516,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,709,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,772,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,792,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [21]:
# 20
df = df.rename(columns = {"Bank_NumOfProducts":"Bank_Products","Bank_HasCrCard":"Bank_CreditCard"})
df

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_Products,Bank_CreditCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [22]:
# 21
df = df.rename(columns = {"Bank_RowNumber":"Row_No","Bank_Customer_ID":"Customer_ID",
                         "Bank_Surname":"Last_Name","Bank_Credit_Score":"Credit_Score",
                         "Bank_Geography":"Country","Bank_Gender":"Sex",
                         "Bank_Tenure":"Salary","Bank_Churn":"Target"})
df

,Row_No,Customer_ID,Last_Name,Credit_Score,Country,Sex,Bank_Age,Salary,Bank_Balance,Bank_Products,Bank_CreditCard,Bank_IsActiveMember,Bank_Salary,Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [23]:
# 22
df_num = df.select_dtypes(['float','int'])
df_num.describe()
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Row_No               10000 non-null  int64
 1   Customer_ID          10000 non-null  int64
 2   Credit_Score         10000 non-null  int64
 3   Bank_Age             10000 non-null  float64
 4   Salary               10000 non-null  int64
 5   Bank_Balance         10000 non-null  float64
 6   Bank_Products        10000 non-null  int64
 7   Bank_CreditCard      10000 non-null  int64
 8   Bank_IsActiveMember  10000 non-null  int64
 9   Bank_Salary          10000 non-null  float64
dtypes: float64(3), int64(7)
memory usage: 781.4 KB

In [24]:
# 23
customers = {
    101: {"Name": "Alice", "City": "Hyderabad"},
    102: {"Name": "Bob", "City": "Chennai"},
    103: {"Name": "Alice", "City": "Hyderabad"},   # Duplicate
    104: {"Name": "David", "City": "Mumbai"},
    105: {"Name": "Bob", "City": "Chennai"},       # Duplicate
    106: {"Name": "Eva", "City": "Delhi"}
}
df4 = pd.DataFrame(customers)
print(df4.duplicated().sum())
df4 = df4.drop_duplicates()
df4

0

            101      102        103     104      105    106
Name      Alice      Bob      Alice   David      Bob    Eva
City  Hyderabad  Chennai  Hyderabad  Mumbai  Chennai  Delhi

In [25]:
# 24
df = df.add_prefix("Customer_")
df

,Customer_Row_No,Customer_Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Country,Customer_Sex,Customer_Bank_Age,Customer_Salary,Customer_Bank_Balance,Customer_Bank_Products,Customer_Bank_CreditCard,Customer_Bank_IsActiveMember,Customer_Bank_Salary,Customer_Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [26]:
# 25
df1 = df[["Customer_Bank_Age","Customer_Bank_Balance","Customer_Bank_Salary"]].astype('float')
df1

      Customer_Bank_Age  Customer_Bank_Balance  Customer_Bank_Salary
0                  42.0                   0.00             101348.88
1                  41.0               83807.86             112542.58
2                  42.0              159660.80             113931.57
3                  39.0                   0.00              93826.63
4                  43.0              125510.82              79084.10
...                 ...                    ...                   ...
9995               39.0                   0.00              96270.64
9996               35.0               57369.61             101699.77
9997               36.0                   0.00              42085.58
9998               42.0               75075.31              92888.52
9999               28.0              130142.79              38190.78

[10000 rows x 3 columns]

In [27]:
df

,Customer_Row_No,Customer_Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Country,Customer_Sex,Customer_Bank_Age,Customer_Salary,Customer_Bank_Balance,Customer_Bank_Products,Customer_Bank_CreditCard,Customer_Bank_IsActiveMember,Customer_Bank_Salary,Customer_Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [28]:
# 26
med = df["Customer_Credit_Score"].median()
df["Customer_Credit_Score"] = df["Customer_Credit_Score"].fillna(med)
df["Customer_Credit_Score"]

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: Customer_Credit_Score, Length: 10000, dtype: int64

In [29]:
# 27
mean = df["Customer_Bank_Salary"].mean()
df["Customer_Bank_Salary"] = df["Customer_Bank_Salary"].fillna(mean)
df["Customer_Bank_Salary"]

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: Customer_Bank_Salary, Length: 10000, dtype: float64

In [30]:
# 28
df = df.drop_duplicates()
df = df.rename(columns= {"Customer_Target":"Target"})
df["Target"] = df["Target"].astype("string")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Customer_Row_No               10000 non-null  int64
 1   Customer_Customer_ID          10000 non-null  int64
 2   Customer_Last_Name            10000 non-null  object
 3   Customer_Credit_Score         10000 non-null  int64
 4   Customer_Country              10000 non-null  object
 5   Customer_Sex                  10000 non-null  object
 6   Customer_Bank_Age             10000 non-null  float64
 7   Customer_Salary               10000 non-null  int64
 8   Customer_Bank_Balance         10000 non-null  float64
 9   Customer_Bank_Products        10000 non-null  int64
 10  Customer_Bank_CreditCard      10000 non-null  int64
 11  Customer_Bank_IsActiveMember  10000 non-null  int64
 12  Customer_Bank_Salary          10000 non-null  float64
 13  Target                        10000 non-null  string
dtypes: float64(3), int64(7), object(3), string(1)
memory usage: 1.1+ MB

In [31]:
df

,Customer_Row_No,Customer_Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Country,Customer_Sex,Customer_Bank_Age,Customer_Salary,Customer_Bank_Balance,Customer_Bank_Products,Customer_Bank_CreditCard,Customer_Bank_IsActiveMember,Customer_Bank_Salary,Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [37]:
# 29
df_copy = df
df_copy = df_copy.rename(columns= {"Customer_Sex":"CustomerGender" , "Customer_Country":"Country"})
df_copy = df_copy.add_prefix("Bank_")
df_copy = df_copy.drop("Bank_Customer_Row_No",axis=1)
df_copy.head(10)

,Bank_Customer_Customer_ID,Bank_Customer_Last_Name,Bank_Customer_Credit_Score,Bank_Country,Bank_CustomerGender,Bank_Customer_Bank_Age,Bank_Customer_Salary,Bank_Customer_Bank_Balance,Bank_Customer_Bank_Products,Bank_Customer_Bank_CreditCard,Bank_Customer_Bank_IsActiveMember,Bank_Customer_Bank_Salary,Bank_Target
0,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,15574012,Chu,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1
6,15592531,Bartlett,822,France,Male,50.0,7,0.00,2,1,1,10062.80,0
7,15656148,Obinna,376,Germany,Female,29.0,4,115046.74,4,1,0,119346.88,1
8,15792365,He,501,France,Male,44.0,4,142051.07,2,0,1,74940.50,0
9,15592389,H?,684,France,Male,27.0,2,134603.88,1,1,1,71725.73,0

In [46]:
# 30
d = pd.read_csv("/Users/abhinavkanchustambham/Documents/programming/DS/python/Tasks/Bank_customer_churn.csv")
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [47]:
print(d.isna().sum())
d.drop_duplicates()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [49]:
d = d.rename(columns= {"CustomerId":"Customer_ID" , "CreditScore":"Credit_Score" , 
                       "EstimatedSalary":"Salary" , "Exited":"Target"})
d[["Age","Balance"]] = d[["Age","Balance"]].astype('float')
d["Target"] = d["Target"].astype('string')
d

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [50]:
median = d['Age'].median()
mean = d['Balance'].mean()
d['Age'] = d['Age'].fillna(median)
d['Balance'] = d['Age'].fillna(mean)
d

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,42.0,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,41.0,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,42.0,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,39.0,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,43.0,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,39.0,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,35.0,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,36.0,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,42.0,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,28.0,1,1,0,38190.78,0

In [52]:
d = d.drop('RowNumber',axis=1)
d

,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,15634602,Hargrave,619,France,Female,42.0,2,42.0,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41.0,1,41.0,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42.0,8,42.0,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39.0,1,39.0,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43.0,2,43.0,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,Obijiaku,771,France,Male,39.0,5,39.0,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35.0,10,35.0,1,1,1,101699.77,0
9997,15584532,Liu,709,France,Female,36.0,7,36.0,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42.0,3,42.0,2,1,0,92888.52,1
9999,15628319,Walker,792,France,Female,28.0,4,28.0,1,1,0,38190.78,0

In [53]:
d.head(10)

,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,15634602,Hargrave,619,France,Female,42.0,2,42.0,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41.0,1,41.0,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42.0,8,42.0,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39.0,1,39.0,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43.0,2,43.0,1,1,1,79084.10,0
5,15574012,Chu,645,Spain,Male,44.0,8,44.0,2,1,0,149756.71,1
6,15592531,Bartlett,822,France,Male,50.0,7,50.0,2,1,1,10062.80,0
7,15656148,Obinna,376,Germany,Female,29.0,4,29.0,4,1,0,119346.88,1
8,15792365,He,501,France,Male,44.0,4,44.0,2,0,1,74940.50,0
9,15592389,H?,684,France,Male,27.0,2,27.0,1,1,1,71725.73,0

In [55]:
d.describe()

,Customer_ID,Credit_Score,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,38.921800,1.530200,0.70550,0.515100,100090.239881
std,7.193619e+04,96.653299,10.487806,2.892174,10.487806,0.581654,0.45584,0.499797,57510.492818
min,1.556570e+07,350.000000,18.000000,0.000000,18.000000,1.000000,0.00000,0.000000,11.580000
25%,1.562853e+07,584.000000,32.000000,3.000000,32.000000,1.000000,0.00000,0.000000,51002.110000
50%,1.569074e+07,652.000000,37.000000,5.000000,37.000000,1.000000,1.00000,1.000000,100193.915000
75%,1.575323e+07,718.000000,44.000000,7.000000,44.000000,2.000000,1.00000,1.000000,149388.247500
max,1.581569e+07,850.000000,92.000000,10.000000,92.000000,4.000000,1.00000,1.000000,199992.480000

In [56]:
d['Target'].value_counts()

Target
0    7963
1    2037
Name: count, dtype: Int64

In [57]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     10000 non-null  int64
 1   Surname         10000 non-null  object
 2   Credit_Score    10000 non-null  int64
 3   Geography       10000 non-null  object
 4   Gender          10000 non-null  object
 5   Age             10000 non-null  float64
 6   Tenure          10000 non-null  int64
 7   Balance         10000 non-null  float64
 8   NumOfProducts   10000 non-null  int64
 9   HasCrCard       10000 non-null  int64
 10  IsActiveMember  10000 non-null  int64
 11  Salary          10000 non-null  float64
 12  Target          10000 non-null  string
dtypes: float64(3), int64(6), object(3), string(1)
memory usage: 1015.8+ KB